name: Basic Build

on:
  workflow_dispatch: # Allows you to run this manually from the Actions tab
  push:
  pull_request:

jobs:
  setup-project:
    name: Setup project on ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Run vercel-preparation.sh
        run: |
          chmod +x ./vercel-preparation.sh
          ./vercel-preparation.sh

      - name: Run script
        run: pnpm --filter frontend run build-trends
